### ISSUE TITLE
Link z readme moze byc w nastepnych latach niepoprawny

### ISSUE THREAD

**Issue by wvffle** [pb-students/3-Przetwarzanie-Sygnalow-i-Obrazow-01-Py#1]
Sa tworzone zazwyczaj nowe grupy

**Comment by wvffle** [comment]
mozesz dac np nazwisko prowadzacego

**Comment by ProgramistycznySwir** [comment]
Dam to i to, link jest wygodny, a jak nie zadziała to niech ktoś szuka
